services:
  api:
    depends_on:
      - db
    build: .
    command: bash scripts/docker-entrypoint.sh dev
    environment:
      - DJANGO_SETTINGS_MODULE=tgs.settings.dev
    ports:
      - 8000:8000
    volumes:
      - .:/app

  db:
    image: postgres:alpine3.18
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=tgs_db
      - POSTGRES_PASSWORD=pwd
    volumes:
      - postgresdata:/var/lib/postgresql/data

  redis:
    image: redis:6.2-alpine
    ports:
      - 6379:6379
    volumes:
      - redisdata:/data

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=pwd
      - PGADMIN_SERVER_JSON_FILE=/pgadmin4/servers.json
    volumes:
      - ./db/servers.json:/pgadmin4/servers.json
    logging:
      driver: none

volumes:
  postgresdata:
  redisdata: