# Generated by Django 5.1.6 on 2025-02-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('phone', models.CharField(max_length=32)),
                ('is_logged_in', models.BooleanField(default=False)),
            ],
        ),
    ]
