# Generated by Django 5.1.6 on 2025-02-19 04:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='subscription',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
