# Generated by Django 5.1.6 on 2025-02-23 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_telegramuser_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.BigIntegerField()),
                ('api_hash', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='api',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.telegramapi'),
        ),
    ]
