# Generated by Django 5.1.6 on 2025-02-23 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_telegramapi_telegramuser_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='subscription',
            field=models.DateField(auto_now=True),
        ),
    ]
