# Generated by Django 5.1.6 on 2025-02-23 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_telegramuser_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='subscription',
            field=models.DateField(),
        ),
    ]
