# Generated by Django 5.1.6 on 2025-02-23 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_alter_telegramuser_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='api',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_connected', to='bot.telegramapi'),
        ),
    ]
