name: Docker Image CI

on:
  push:
    branches: ["main"]
  # pull_request:
  #   branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: dragonsteam/group-sender:latest

jobs:
  publish:
    name: publish image
    runs-on: self-hosted
    # runs-on: ubuntu:latest

    steps:
      - uses: actions/checkout@v4
      - name: Login
        run: |
          echo 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 | docker login ghcr.io -u dragonsteam --password-stdin

        # echo ${{secrets.GHCR_TOKEN}} | docker login ghcr.io -u dragonsteam --password-stdin
      - name: Build and Publish
        run: |
          docker build . --file Dockerfile --tag ${{env.REGISTRY}}/${{env.IMAGE_NAME}}
          docker push ${{env.REGISTRY}}/${{env.IMAGE_NAME}}
